node {
    checkout scm
    def container = docker.image('node:lts-buster-slim').run('-p 3000:3000')
    stage('Build') {
        container {
            sh 'npm install'
        }
    }
    stage('Test') {
        container {
            sh './jenkins/scripts/test.sh'
        }
    }
    stage('Manual Approval') {
        input(message: 'Lanjutkan ke tahap Deploy?', ok: 'Deploy')
    }
    stage('Deploy') {
        container {
            sh './jenkins/scripts/deliver.sh' 
            sleep(1 * 60)
            sh './jenkins/scripts/kill.sh'
        }
    }
}
