pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 3000:3000'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Manual Approval') {
            steps {
                input(message: 'Lanjutkan ke tahap Deploy?', ok: 'Deploy')
            }
        }
        stage('Deploy') { 
            def sleepTime = 1 * 60 // 1 minute
            steps {
                sh './jenkins/scripts/deliver.sh' 
                // input message: 'Sudah selesai menggunakan React App? (Klik "Proceed" untuk mengakhiri)'             
                sleep(sleepTime)
                sh './jenkins/scripts/kill.sh' 
            }
        }
    }
}